name: Bug Report
title: "[BUG] "
description: Report a problem you're having
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > We (the developers) don't actively check issues anymore. We might not get to your issue unless it may be important (like if it's about a feature breaking). Sorry about that.
        ### **Instructions**
        - Before you open this report, please [check the Wiki first](https://bloxstraplabs.com/wiki/help). Most common problems will be addressed here.
        - Make sure you are using the [latest version of Bloxstrap](https://github.com/bloxstraplabs/bloxstrap/releases/latest). Your report won't be valid if you aren't.
        - If you are getting a Bloxstrap Exception error, please attach a copy of the provided log file. There is a button on the dialog that locates it for you.
        - Your report may be closed as stale if you don't respond in a good amount of time.
  - type: checkboxes
    id: terms
    attributes:
      label: I have...
      options:
        - label: I have read the instructions, and I didn't find a solution in the Wiki.
          required: true
        - label: I am using the latest version of Bloxstrap.
          required: true
  - type: input
    id: version
    attributes:
      label: Bloxstrap Version
      description: "What version of Bloxstrap are you using? Find it in the 'About' section of the Settings"
      placeholder: "v1.0.0"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What problem did you encounter?
      description: Provide a good description of the problem you're having. Screenshots too please.
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: How do you reproduce the problem?
      description: Write down steps to cause the problem, from start to finish, if you can.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
  - type: textarea
    id: log
    attributes:
      label: Bloxstrap Log
      description: If you're getting a Bloxstrap Exception error, upload your log file here. Otherwise, just leave it empty.
      value: "N/A"
      render: text
